spring:
  datasource:
    dynamic:
      ##分析sql工具生产建议关掉，会影响性能
      p6spy: false
      druid: #以下是全局默认值，可以全局更改
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        time-between-log-stats-millis:
        stat-sqlmax-size:
        min-evictable-idle-time-millis: 300000
        max-evictable-idle-time-millis:
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout:
        use-global-datasource-stat:
        async-init:
        clear-filters-enable:
        reset-stat-enable:
        not-full-timeout-retry-count:
        max-wait-thread-count:
        fail-fast:
        phyTimeout-millis:
        keep-alive:
        pool-prepared-statements: true
        init-variants:
        init-global-variants:
        use-unfair-lock:
        kill-when-socket-read-timeout:
        connection-properties:
        max-pool-prepared-statement-per-connection-size: 20
        init-connection-sqls:
        share-prepared-statements:
        connection-errorretry-attempts:
        break-after-acquire-failure:
        filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall（使用了p6spy测试环境先关闭wall）
      primary: mysql
      datasource:
        mysql:
          url: jdbc:mysql://10.15.194.53:8082/rpt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
          username:  rpt_read
          password:  rptread123ABC
          driver-class-name: com.mysql.cj.jdbc.Driver
        vertical:
          url: jdbc:vertica://10.15.194.53:8888/FNVDP
          username:  FNRPT
          password:  Feck6aSwFg
          driver-class-name: com.vertica.jdbc.Driver
      hikari:
        max-lifetime: 500000
  boot:
    admin:
      client:
        url: http://localhost:8755

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    logfile:
      enabled: true         #可在线查看日志

logging:
  file:
    name: logs/report-generate/boot_admin.log
  level:
    com.fn.bi.report.generate.mapper: DEBUG

backend:
  prod-target-path: D:/opt/backend/prod/target/
  prod-template-path: D:/opt/backend/prod/template/
  test-target-path: D:/opt/backend/test/target/
  test-template-path: D:/opt/backend/test/template/
