#spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:8755
#  datasource:
#    username:  root
#    password:  123456
#    url: jdbc:mysql://10.15.194.34:8080/backend_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
#    hikari:
#      max-lifetime: 500000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
#    logfile:
#      enabled: true         #可在线查看日志
#
#logging:
#  file:
#    name: D:\opt\logs\report-login\boot_admin.log
#  level:
#    com.fn.bi.report.login.mapper: DEBUG
