server:
  port: 8083

spring:
  application:
    name: yoci-api

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.15.194.34:8080/mail_report?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    hikari:
      max-lifetime: 500000

security:
  oauth2:
    client:
      client-id: gateWay
      client-secret: gateWay
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
