package com.fn.bi.report.login.mapper.generator;

import java.util.List;

import com.fn.bi.report.login.entity.BackendPermission;
import com.fn.bi.report.login.entity.BackendPermissionExample;
import org.apache.ibatis.annotations.Param;

public interface BackendPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    long countByExample(BackendPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int deleteByExample(BackendPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int insert(BackendPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int insertSelective(BackendPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    BackendPermission selectOneByExample(BackendPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    BackendPermission selectOneByExampleSelective(@Param("example") BackendPermissionExample example, @Param("selective") BackendPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    List<BackendPermission> selectByExampleSelective(@Param("example") BackendPermissionExample example, @Param("selective") BackendPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    List<BackendPermission> selectByExample(BackendPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    BackendPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BackendPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    BackendPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    BackendPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BackendPermission record, @Param("example") BackendPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BackendPermission record, @Param("example") BackendPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BackendPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BackendPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BackendPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}