package com.fn.bi.report.login.mapper.generator;

import java.util.List;

import com.fn.bi.report.login.entity.BackendRole;
import com.fn.bi.report.login.entity.BackendRoleExample;
import org.apache.ibatis.annotations.Param;

public interface BackendRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    long countByExample(BackendRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int deleteByExample(BackendRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int insert(BackendRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int insertSelective(BackendRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    BackendRole selectOneByExample(BackendRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    BackendRole selectOneByExampleSelective(@Param("example") BackendRoleExample example, @Param("selective") BackendRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    List<BackendRole> selectByExampleSelective(@Param("example") BackendRoleExample example, @Param("selective") BackendRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    List<BackendRole> selectByExample(BackendRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    BackendRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BackendRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    BackendRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    BackendRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BackendRole record, @Param("example") BackendRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BackendRole record, @Param("example") BackendRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BackendRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BackendRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BackendRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}