package com.fn.bi.report.login.mapper.generator;

import java.util.List;

import com.fn.bi.report.login.entity.BackendAdmin;
import com.fn.bi.report.login.entity.BackendAdminExample;
import org.apache.ibatis.annotations.Param;

public interface BackendAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    long countByExample(BackendAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int deleteByExample(BackendAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int insert(BackendAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int insertSelective(BackendAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    BackendAdmin selectOneByExample(BackendAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    BackendAdmin selectOneByExampleSelective(@Param("example") BackendAdminExample example, @Param("selective") BackendAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    List<BackendAdmin> selectByExampleSelective(@Param("example") BackendAdminExample example, @Param("selective") BackendAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    List<BackendAdmin> selectByExample(BackendAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    BackendAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BackendAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    BackendAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    BackendAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BackendAdmin record, @Param("example") BackendAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BackendAdmin record, @Param("example") BackendAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BackendAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BackendAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BackendAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}