#spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:8755
#  mail:
#    host: 10.202.144.31
#    port: 25
#    username: bi@feiniu.com
#    password: Fn123!@#
#    default-encoding: UTF-8
#    from: bi@feiniu.com
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
#    logfile:
#      enabled: true         #可在线查看日志
#
#logging:
#  file:
#    name: D:\opt\logs\report-send\boot_admin.log
#
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout: 500000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 500000
#backend:
#  prod-target-path: D:/opt/backend/prod/target/
#  test-target-path: D:/opt/backend/test/target/