#spring:
#  datasource:
#    username:  root
#    password:  20Bi!bacKend
#    url: jdbc:mysql://10.208.29.1:3306/mail_report?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
#    hikari:
#      max-lifetime: 500000
#
#  boot:
#    admin:
#      client:
#        url: http://10.208.29.1:8755
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
#    logfile:
#      enabled: true         #可在线查看日志
#
#logging:
#  file:
#    name: logs/report-develop/boot_admin.log
##  level:
##    com.fn.bi.report.develop.mapper: DEBUG
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#
#backend:
#  prod-target-path: /opt/backend/prod/target/
#  prod-template-path: /opt/backend/prod/template/
#  test-target-path: /opt/backend/test/target/
#  test-template-path: /opt/backend/test/template/
